export const eventsContent = {
  en: {
    upcoming: "Upcoming",
    past: "Past events",
    ongoing: "Ongoing",
    emptyTitle: "The next date is still taking shape.",
    emptyDescription:
      "We are preparing new activities with our partners. Check back soon or tell us what kind of workshop you would like to join.",
    emptyAction: "Suggest an activity",
    date: "Date",
    location: "Location",
    audience: "Who it’s for",
    details: "Open event details",
    highlights: "What happened",
    upcomingHighlights: "What you’ll explore",
    eventEnded: "This event has ended",
    signup: "Sign up for this event",
    signupSoon: "Registration opens soon",
    close: "Close event",
    category: {
      workshop: "Workshop",
      course: "Course",
      activity: "Activity",
      competition: "Competition",
    },
  },
  ro: {
    upcoming: "Urmează",
    past: "Evenimente trecute",
    ongoing: "În desfășurare",
    emptyTitle: "Următoarea dată încă prinde contur.",
    emptyDescription:
      "Pregătim activități noi împreună cu partenerii noștri. Revino curând sau spune-ne ce fel de workshop ți-ar plăcea să găsești aici.",
    emptyAction: "Propune o activitate",
    date: "Data",
    location: "Locația",
    audience: "Cui se adresează",
    details: "Deschide detaliile evenimentului",
    highlights: "Ce am făcut",
    upcomingHighlights: "Ce vom face",
    eventEnded: "Acest eveniment s-a încheiat",
    signup: "Înscrie-te la acest eveniment",
    signupSoon: "Înscrierile se deschid în curând",
    close: "Închide evenimentul",
    category: {
      workshop: "Workshop",
      course: "Curs",
      activity: "Activitate",
      competition: "Competiție",
    },
  },
} as const;
