export const siteConfig = {
  name: "ScripticX",
  url: "https://www.scripticx.org",
  logo: "/icons/notification-icon-512.png",
  descriptions: {
    ro: "Pregătire la informatică, probleme de programare și un spațiu complet pentru învățare, proiecte și colaborare.",
    en: "Informatics education, coding problems and a complete workspace for learning, projects and collaboration.",
  },
  keywords: [
    "ScripticX",
    "pregătire la informatică",
    "pregătire informatică",
    "probleme de informatică",
    "probleme de programare",
    "învățare programare",
    "MiniScript+",
    "coding platform",
    "coding problems",
    "programming practice",
    "learn programming",
    "interactive coding",
    "education",
    "software development",
  ],
} as const;
